#!/usr/bin/env python3
"""Render the exercise sheets and the GitHub task descriptions out of `config/exercises_localization.json`.

    python3 tools/make_lab_docs.py            # write docs/handout/lab-*.md, .github/issues/*.md, README block
    python3 tools/make_lab_docs.py --check    # fail if the files on disk are not what the JSON says (CI)
    python3 tools/make_lab_docs.py --stdout e1_nn

**Why generated.** The task description exists in three places at once — the sheet a group holds, the GitHub
issue they are pointed at, and the grader that decides their mark — and a threshold that is edited in one of
the three and not the others is not a documentation bug but a mark that was never achievable. So the JSON holds
the criteria, their points, their thresholds and the measured numbers, and this tool holds the prose layout. It
is the same arrangement `tools/make_handout.py` uses for the four graded MCL sheets, for the same reason.

**What stays hand-written.** The long-form teaching documents (`docs/icp.md`, `docs/mcl.md`, the measured
numbers in `docs/verification.md`) and the L1 … L4 sections of `docs/exercises.md`: those argue, and an
argument that is generated is not written. A sheet is a contract, and a contract is generated.
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXERCISE_FILE = os.path.join(ROOT, "config", "exercises_localization.json")
HANDOUT = os.path.join(ROOT, "docs", "handout")
ISSUES = os.path.join(ROOT, ".github", "issues")
README = os.path.join(ROOT, "README.md")
BEGIN = "<!-- lab-exercises:begin — generated by tools/make_lab_docs.py from config/exercises_localization.json -->"
END = "<!-- lab-exercises:end -->"
MARK = "<!-- lab-exercise:"                      # one per issue body; publish_issues.sh looks for it
# Where the numbers on a sheet came from. A sheet that quotes 60 mm without saying which run produced it is a
# rumour, and the section is the difference between “checkable” and “trust me”.
VERIF = "`docs/verification.md` §19 (and §14 for the four MCL drives)"


def load(path: str = EXERCISE_FILE) -> dict:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def task_points(ids: str, task_file: str) -> float:
    """The points of the tasks a graded exercise is marked on, read from the task file itself.

    Not copied into this file's JSON: the four MCL tasks are worth what `config/tasks_localization.json` says
    they are worth, and a second place to edit a mark scheme is a second place to get it wrong.
    """
    with open(os.path.join(ROOT, task_file), encoding="utf-8") as handle:
        tasks = {t["id"]: t for t in json.load(handle)["tasks"]}
    return float(sum(tasks[i]["points"] for i in ids.split(",") if i in tasks))


def points_of(book: dict, ex_id: str) -> float:
    for e in book["exercises"]:
        if e["id"] == ex_id:
            if e.get("criteria"):
                return float(sum(c["points"] for c in e["criteria"]))
            g = e.get("graded") or {}
            if g.get("task"):
                return task_points(g["task"], g.get("task_file", "config/tasks_localization.json"))
            return 0.0
    return 0.0


def header(book: dict, e: dict) -> list:
    pts = points_of(book, e["id"])
    line = (f"# {e['code']} — {e['title']}\n\n"
            f"*{e['visit']} · {e['minutes']} minutes of a 180-minute session · "
            f"{pts:g} points · file `{e['file']}`*")
    out = [line, "", f"Command that decides it: `{e['run']}`", ""]
    if e.get("entry"):
        out += [f"Your function: `{e['entry']}`", ""]
    return out


def body(book: dict, e: dict) -> list:
    out = []
    for para in e.get("brief", []):
        out += [para, ""]
    out += ["## Do this, in this order", ""]
    for i, step in enumerate(e.get("steps", []), 1):
        out.append(f"{i}. {step}")
    out += ["", "## Protocol — what goes in the write-up", ""]
    for item in e.get("protocol", []):
        out.append(f"* {item}")
    out += ["", "## Hand in", ""]
    for item in e.get("deliverables", []):
        out.append(f"* {item}")
    out += ["", "## What is measured", ""]
    if e.get("criteria"):
        out += ["| criterion | pts | what it measures | the ask | measured here |",
                "|---|---|---|---|---|"]
        for c in e["criteria"]:
            cells = [f"`{c['id']}`", str(c["points"]), c["what"], c["ask"],
                     c.get("measured", "—").replace("|", "/")]
            out.append("| " + " | ".join(cells) + " |")
        out.append("")
        out.append("*The `measured here` column is the reference solution "
                   "(`" + e.get("solution", "—") + "`) run through the command above; the ask is the threshold in "
                   "`config/exercises_localization.json`. Both are reproduced by "
                   "`python3 tools/lab_check.py --check`. " + VERIF + " has the runs.*")
    else:
        n = len(e["graded"]["task"].split(","))
        out += [f"Graded by the simulator's own grader on {n} task{'' if n == 1 else 's'} in "
                f"`{e['graded']['task_file']}` ({e['graded']['task']}). The criteria and the points are the task "
                f"file's own — the same file the grader loads — and the numbers it produced are in " + VERIF + ".", ""]
    if e.get("measured"):
        out += ["", "### The two runs to compare (measured)", "", "```",
                json.dumps(e["measured"], indent=2, ensure_ascii=False), "```", ""]
    if e.get("teaches"):
        out += ["", f"**What this is for.** {e['teaches']}", ""]
    return out


def sheet(book: dict, e: dict) -> str:
    return "\n".join(header(book, e) + body(book, e)).rstrip() + "\n"


def issue(book: dict, e: dict) -> str:
    """The GitHub issue body: the same contract, with the parts a repository issue needs and a sheet does not."""
    pts = points_of(book, e["id"])
    lines = [f"Title: [{e['visit']}] {e['code']} — {e['title']} ({pts:g} pts)", "",
             f"Labels: `lab-{e['visit'].lower()}`, `exercise`, `localisation`", ""]
    lines += header(book, e)[2:]
    for para in e.get("brief", []):
        lines += [para, ""]
    lines += ["**Prepare** (before the session): read the section of `docs/exercises.md` this issue is the task "
              "description for, and the two lines of the library it names. Everything else happens in the room.",
              "", "**Command that decides it**", "", "```", e["run"], "```", "",
              "**Criteria and points** (from `config/exercises_localization.json`, generated here so the issue "
              "cannot disagree with the grader)", ""]
    if e.get("criteria"):
        lines += ["| criterion | pts | the ask |", "|---|---|---|"]
        for c in e["criteria"]:
            lines.append(f"| `{c['id']}` | {c['points']} | {c['ask']} |")
    else:
        lines.append(f"See `{e['graded']['task_file']}`, task(s) `{e['graded']['task']}`.")
    lines += ["", "Deliverables and the protocol list are in the sheet: "
              f"`docs/handout/lab-{e['id']}.md`.", "",
              f"{MARK} {e['id']} -->"]           # what .github/publish_issues.sh recognises as its own
    return "\n".join(lines).rstrip() + "\n"


def readme_block(book: dict) -> str:
    rows = ["| visit | exercise | what you write | points | the command that grades it |",
            "|---|---|---|---|---|"]
    for e in book["exercises"]:
        pts = points_of(book, e["id"])
        rows.append(f"| {e['visit']} | **{e['code']}** {e['title']} | `{e['file'].split('/')[-1]}` | "
                    f"{pts:g} | `{e['run']}` |")
    total = sum(points_of(book, e["id"]) for e in book["exercises"])
    by_visit = collections.defaultdict(list)
    for e in book["exercises"]:
        by_visit[e["visit"]].append(e["code"])
    plan = " · ".join(f"**{v['id']}** {v['minutes']} min {v['topic']} → {' + '.join(by_visit[v['id']])}"
                      for v in book["visits"])
    rows += ["",
             f"Four 180-minute sessions, **{total:g} points**. {plan}. Three of the five exercises (E1, E2, E4) "
             "are graded by `python3 tools/lab_check.py` on seeded synthetic data, need no simulator and can be "
             "re-run as often as you like during the session; the two on the robot (E3, E5) are graded by the "
             "simulator's own grader. The sheet for each one is `docs/handout/lab-<id>.md`, the long-form task "
             "text with the numbers behind it is [`docs/exercises.md`](docs/exercises.md), what a tutor prepares "
             "is [`docs/lab-plan.md`](docs/lab-plan.md), and every threshold in the table is a measurement listed, "
             "with the run that produced it, in [`docs/verification.md`](docs/verification.md)."]
    return BEGIN + "\n" + "\n".join(rows) + "\n" + END


def write(path: str, text: str, check: bool, missing: list) -> None:
    old = open(path, encoding="utf-8").read() if os.path.isfile(path) else None
    if old == text:
        return
    if check:
        missing.append(path + ("" if old is not None else " (does not exist yet)"))
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"  wrote {os.path.relpath(path, ROOT)}")


def patch_readme(book: dict, check: bool, missing: list) -> None:
    text = open(README, encoding="utf-8").read() if os.path.isfile(README) else ""
    block = readme_block(book)
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _old, tail = rest.split(END, 1)
        new = head + block + tail
    else:
        new = text.rstrip() + "\n\n" + block + "\n"
    if new != text:
        write(README, new, check, missing)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if the generated files are out of date")
    ap.add_argument("--stdout", metavar="EXERCISE", help="print one sheet instead of writing anything")
    a = ap.parse_args()
    book = load()
    if a.stdout:
        print(sheet(book, ex_one(book, a.stdout)))
        return 0
    missing = []
    for e in book["exercises"]:
        write(os.path.join(HANDOUT, f"lab-{e['id']}.md"), sheet(book, e), a.check, missing)
        write(os.path.join(ISSUES, f"{e['id']}.md"), issue(book, e), a.check, missing)
    patch_readme(book, a.check, missing)
    if missing:
        print("make_lab_docs: these files do not match config/exercises_localization.json:", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
        print("run  python3 tools/make_lab_docs.py  and commit the result.", file=sys.stderr)
        return 1
    return 0


def ex_one(book: dict, ex_id: str) -> dict:
    for e in book["exercises"]:
        if e["id"] == ex_id:
            return e
    raise SystemExit(f"no exercise {ex_id!r}")


if __name__ == "__main__":
    raise SystemExit(main())
